# tsfresh python library for feature extraction

In [14]:
import Helper as hp
from tsfresh import extract_features
import pandas as pd
import numpy as np

In [2]:
input_data = hp.read_input_data()
test_data = hp.read_test_data()
Y2 = hp.read_Y(os.getcwd()+"/Data/Y2.csv")
Y2 = [int(y2) for y2 in Y2]
input_data_df = pd.DataFrame.from_dict(input_data)
input_data_df["valid_or_not"] = Y2
features1 = hp.time_series2features(input_data["ramposition"],
                                    input_data["ramposition_time"])

In [3]:
input_data_df.head(5)

ramposition  \
0  [0.071227, 0.070499, 0.06996, 0.06934, 0.06879...   
1  [0.071227, 0.070506, 0.069968, 0.069349, 0.068...   
2  [0.071227, 0.07048, 0.069943, 0.06933, 0.06878...   
3  [0.071227, 0.070522, 0.069982, 0.069359, 0.068...   
4  [0.071227, 0.070501, 0.069961, 0.069342, 0.068...   

                                    ramposition_time  \
0  [0.00669, 0.015201, 0.021505, 0.028743, 0.0350...   
1  [0.007142, 0.016141, 0.022851, 0.03058, 0.0373...   
2  [0.0074, 0.017065, 0.023998, 0.03193, 0.038993...   
3  [0.007268, 0.016227, 0.023072, 0.030986, 0.037...   
4  [0.006897, 0.015651, 0.022148, 0.029611, 0.036...   

                                  injection_pressure  \
0  [0.0, 2836400.0, 5461800.0, 7290900.0, 9201700...   
1  [0.0, 2719500.0, 5223100.0, 6981400.0, 8817000...   
2  [0.0, 2985100.0, 5853000.0, 7770100.0, 9795700...   
3  [0.0, 2510300.0, 4774100.0, 6414900.0, 8109300...   
4  [0.0, 2795600.0, 5384200.0, 7191900.0, 9078600...   

                             injection_pressure_time  \
0  [0.0, 0.00669, 0.015201, 0.021505, 0.028743, 0...   
1  [0.0, 0.007142, 0.016141, 0.022851, 0.03058, 0...   
2  [0.0, 0.0074, 0.017065, 0.023998, 0.03193, 0.0...   
3  [0.0, 0.007268, 0.016227, 0.023072, 0.030986, ...   
4  [0.0, 0.006897, 0.015651, 0.022148, 0.029611, ...   

                                     sensor_pressure  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                sensor_pressure_time  valid_or_not  
0  [0.00669, 0.015201, 0.021505, 0.028743, 0.0350...             1  
1  [0.007142, 0.016141, 0.022851, 0.03058, 0.0373...             1  
2  [0.0074, 0.017065, 0.023998, 0.03193, 0.038993...             1  
3  [0.007268, 0.016227, 0.023072, 0.030986, 0.037...             1  
4  [0.006897, 0.015651, 0.022148, 0.029611, 0.036...             1

In [23]:
ram_time = input_data_df.ramposition_time.to_numpy()[0]
injection_pressure_time = input_data_df.injection_pressure_time.to_numpy()[0]
sensor_pressure_time = input_data_df.sensor_pressure_time.to_numpy()[0]
vec_ram_time = np.array(ram_time)
vec_injection_time = np.array(injection_pressure_time)
vec_sensor_time = np.array(sensor_pressure_time)
# print(len(vec_ram_time))
# print(len(vec_injection_time))
# print(len(vec_sensor_time))

print(vec_ram_time[1:5])
print(vec_injection_time[1:5])
print(vec_sensor_time[1:5])

[0.015201 0.021505 0.028743 0.035094]
[18.764668 19.014668 19.514668 19.764668 20.000099]
[18.764668 19.014668 19.514668 19.764668 20.000099]


## TODO:
- The time steps are the same for all sensor measurements, therefore tsfresh can be applied as truly time series multivariate problem. Otherwise we would need a little bit of more transformations.